version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./infra/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - bot

  bot:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/app
    env_file: .env
